name: QuickWarp
version: 1.0.4
main: me.prime.quickwarp.QuickWarp
api-version: 1.19

commands:
  qw:
    description: Teleports the player to the specified dimension.
    usage: /qw <dimension>
    permission: quickwarp.use

# config.yml
permissions:
  quickwarp.use:
    description: Use quickwarp command
    default: true