name: QuickWarp
version: ${version}
main: me.prime.quickwarp.QuickWarp
api-version: 1.20

commands:
  qw:
    description: Teleports the player to the specified dimension.
    usage: /qw <dimension>
    permission: quickwarp.use

permissions:
  - name: quickwarp.use
    description: Allows the player to use the /qw command.
    default: op